#General settings
host: 0.0.0.0
port: $NATS_PORT

//ping_interval = 60s
//ping_max = 5

ping_interval = 2s
ping_max = 1

# Various server level options
# ...

# The following sections are maps with a set of (nested) properties


gateway {
  # Configuration map for gateway. Gateways are used to connected clusters.
}

leafnodes {
  # Configuration map for leafnodes. LeafNodes are lightweight clusters.
}

mqtt {
  # Configuration map for mqtt. Allow clients to connect via mqtt protocol.
}

websocket {
  # Configuration map for websocket. Allow clients to connect via websockets.
}

mappings {
  # Subject mappings for default account
  # When accounts are defined this section must be in the account map
}

jetstream {
  store_dir: nats_storage

  # 1GB
  max_memory_store: 1073741824

  # 10GB
  max_file_store: 10737418240
}
